# FROM openjdk:11-jdk-alpine
# EXPOSE 8080
# ADD target/devops-spring-boot.jar devops-spring-boot.jar
# ENTRYPOINT [ "java","-jar","/devops-spring-boot.jar"]

FROM adoptopenjdk:11-jre-hotspot
 
# Set the working directory.
WORKDIR /usr/src/app
 
# Copy the packaged JAR file from the build stage.
COPY --from=build /usr/src/app/target/*.jar devops-spring-boot.jar
 
EXPOSE 8080 
# Specify the command to run on container start.
ENTRYPOINT ["java","-jar","devops-spring-boot.jar"]